### ISSUE TITLE
关于版头和子版块隐藏

### ISSUE THREAD

**Issue by shangjiaxuan** [ymback/NGA-CLIENT-VER-OPEN-SOURCE#105]
如题，不知道如何用开源客户端浏览版头的部分。
还有，可能是操作问题，只能隐藏子版面内容，开启之后要求刷新，但是退回去进行刷新之前屏蔽会恢复，从而无法保存子版块非屏蔽的状态。

**Comment by shangjiaxuan** [comment]
刚刚重新进行了测试，发现默认开启的子板块可以变换，非默认的才会出现问题

测试的平台：华为mate9 系统版本 MHA-AL00 8.0.0.357

**Comment by Justwen** [comment]
能不能举一个具体的例子

**Comment by Justwen** [comment]
代码已提交
