### ISSUE TITLE
2.1.00版本进帖子就闪退

### ISSUE THREAD

**Issue by luojianxhlxt** [ymback/NGA-CLIENT-VER-OPEN-SOURCE#106]
平板是华为M3的docomo定制版，webview只有chrome stable

![screenshot_20181225-205233](https://user-images.githubusercontent.com/8614534/50422709-9c748580-0887-11e9-9eee-7864098c890b.png)
![screenshot_20181225-205240](https://user-images.githubusercontent.com/8614534/50422711-9e3e4900-0887-11e9-8da1-419b7b48ac23.png)
![screenshot_20181225-205255](https://user-images.githubusercontent.com/8614534/50422712-a0a0a300-0887-11e9-9202-7ba760d40f59.png)
![screenshot_20181225-205308](https://user-images.githubusercontent.com/8614534/50422714-a26a6680-0887-11e9-8cf7-213ec1827358.png)

**Comment by Justwen** [comment]
试试 最新版本
https://www.pgyer.com/fucknga

**Comment by Justwen** [comment]
那就没办法了，系统缺少组件

**Comment by luojianxhlxt** [comment]
忘记什么版本开始，居然可以进帖子了。
