### ISSUE TITLE
切换app会导致列表页无法显示

### ISSUE THREAD

**Issue by KarlManong** [ymback/NGA-CLIENT-VER-OPEN-SOURCE#110]
手机是小米8，系统最新的稳定版10.2.2.0
复现方式：
进入帖子详情页，然后切换下任务。
再从详情页返回，列表页就不展示了。

**Comment by KarlManong** [comment]
补个图：
![gif](https://drive.google.com/open?id=1kQPDSs-0Njbi_wjUSvKqi0pEuTwea87E)

**Comment by Justwen** [comment]
模拟器复现不了。。。

**Comment by Justwen** [comment]
http://www.pgyer.com/fucknga 试试最新的版本

**Comment by Justwen** [comment]
已修复
