### ISSUE TITLE
访问高层建筑时严重卡顿

### ISSUE THREAD

**Issue by simonsmh** [ymback/NGA-CLIENT-VER-OPEN-SOURCE#116]
随便找个访问上w楼层的帖子就可复现

**Comment by ymback** [comment]
我估摸着是算第一页的贴条的html

**Comment by simonsmh** [comment]
切其他楼层也会很卡

比如这个 https://bbs.nga.cn/read.php?tid=15923050&_ff=-447601

**Comment by Justwen** [comment]
已经改好了

**Comment by Justwen** [comment]
https://www.pgyer.com/fucknga 试试最新版
