### ISSUE TITLE
标题转码

### ISSUE THREAD

**Issue by simonsmh** [ymback/NGA-CLIENT-VER-OPEN-SOURCE#117]
![IMG_20190326_160529](https://user-images.githubusercontent.com/9512067/54980745-8179f480-4fe1-11e9-9b65-f10344949e4d.jpg)
如图

**Comment by Justwen** [comment]
具体哪个帖子？

**Comment by Justwen** [comment]
具体哪个帖子？

**Comment by Justwen** [comment]
具体哪个帖子？

**Comment by simonsmh** [comment]
https://bbs.nga.cn/read.php?tid=16762109

**Comment by Justwen** [comment]
已解决

**Comment by Justwen** [comment]
已解决
