### ISSUE TITLE
与米9深色模式不兼容

### ISSUE THREAD

**Issue by mynameismu12332** [ymback/NGA-CLIENT-VER-OPEN-SOURCE#119]
https://imgchr.com/i/AUhzZV
https://imgchr.com/i/AU4SaT
效果图 正常与不正常

**Comment by mynameismu12332** [comment]
第一次启动应用时打开帖子就是黑乎乎效果 以后就正常了

**Comment by Justwen** [comment]
已修改 https://www.pgyer.com/fucknga

**Comment by Justwen** [comment]
已修改 https://www.pgyer.com/fucknga 试一下

**Comment by mynameismu12332** [comment]
ok了 嘿嘿嘿

**Comment by zynisacoolman** [comment]
Keystore file '/Users/zyn/github/NGA-CLIENT-VER-OPEN-SOURCE/nga_phone_base_3.0/..\keystore\nga.jks' not found for signing config 'signingConfig'.

编译无法完成什么原因

**Comment by Justwen** [comment]
你没有签名，需要自己创建一个
