### ISSUE TITLE
vtuber区谢拉推特搬运的帖子加载失败无法打开

### ISSUE THREAD

**Issue by zhongjie10086** [ymback/NGA-CLIENT-VER-OPEN-SOURCE#121]
网址是这个http://bbs.nga.cn/read.php?tid=16445802

**Comment by Justwen** [comment]
用最新的代码测试没有问题

**Comment by simonsmh** [comment]
什么时候发新版？这个bug还是挺影响使用的。

**Comment by Justwen** [comment]
我没带复现，需要提供下复现路径

**Comment by simonsmh** [comment]
2.1.8版本 去vtuber区找这个帖子应该就能100%复现了呀

**Comment by Justwen** [comment]
https://img.nga.178.com/attachments/mon_201904/08/-7Q5-bn8eZ2cT3cSu0-1rc.jpeg

**Comment by simonsmh** [comment]
原来发新版了 issue可以关闭了
