### ISSUE TITLE
子版块显示双搜索icon，缺少收藏功能

### ISSUE THREAD

**Issue by simonsmh** [ymback/NGA-CLIENT-VER-OPEN-SOURCE#123]
![Screenshot_2019-04-07-15-32-01-291_gov anzong androidnga](https://user-images.githubusercontent.com/9512067/55680281-5c26a800-594a-11e9-9a65-41bb22fefd2c.png)
且后者并不是搜索功能是热贴。

**Comment by Justwen** [comment]
需要提供下该版面的url

**Comment by simonsmh** [comment]
https://bbs.nga.cn/thread.php?stid=16667422

**Comment by Justwen** [comment]
最新版本已修复
