### ISSUE TITLE
无法找到置顶/版头

### ISSUE THREAD

**Issue by Michael-LM** [ymback/NGA-CLIENT-VER-OPEN-SOURCE#130]
1.版面内右上角选项只有热帖、精华区、收藏夹等，没有置顶帖/版头

2.回帖后自动刷新功能似乎没有生效

3.有时候手动刷新时刷新的旋转图标不会消失

**Comment by Justwen** [comment]
1. 网页端没找到这个接口
2. 这个bug解决起来比较麻烦，有时间再改
3. 下次发版修复
