### ISSUE TITLE
无法登陆或访问版块 - HTTP 403 Forbidden

### ISSUE THREAD

**Issue by lang-jason** [ymback/NGA-CLIENT-VER-OPEN-SOURCE#131]
OS: Android 9
Model: Samsung S10e (SM-G970F)
IP Location: Australia

您好，
我无法在app上访问任何版块，或是登陆NGA账号。报错提示 “HTTP 403 Forbidden” 。
请问会是什么原因造成的呢？尝试用VPN连回中国IP也无法访问，求解决方法。

感谢，
Jason L

**Comment by Justwen** [comment]
请先确认网页端是否可以正常访问

**Comment by lang-jason** [comment]
> 请先确认网页端是否可以正常访问

网页版是可以访问的

今天再次试了试，直接点击版块无法访问
但是可以登录了，并且登陆之后使用正常

虽然不知道为什么会出现这种情况，但能用就ok，感谢

**Comment by hsj1992** [comment]
@lang-jason 我也有一样的情况。
登录状态下有出现 http 403 forbidden，于是想说清除重置下app，结果依旧。
在看到你说的情况后我尝试登录再访问板块，可以正常访问和打开帖子了。

有发现些情况，不知道有没有关系：
1.当时尝试访问bbs.ngacn.cc这个网址会先是网页错误然后再跳转到bbs.nga.cn，现在不会错误而是直接跳转了；
2.nga.donews.com是挂了的状态；
3.nga.178.com所使用的https证书 *.178.com
在2019/11/23过期了；
4.网页访问bbs.nga.cn无法登录帐号，只能在nga.178.com登录才能成功。
