### ISSUE TITLE
无法使用扫码登录

### ISSUE THREAD

**Issue by ccboxes** [ymback/NGA-CLIENT-VER-OPEN-SOURCE#134]
目前nga官方端使用的域名是ngabbs.com，导致无法扫码登录，请在域名选择中添加ngabbs.com

**Comment by Justwen** [comment]
试了网页端也无法登录

**Comment by ccboxes** [comment]
> 试了网页端也无法登录

可以登录，前提是网页端和安卓客户端使用同一个域名，NGA有四五个域名可以进入，cookie不相通非常麻烦。

**Comment by Justwen** [comment]
复现了，下个版本修复
