### ISSUE TITLE
希望能屏蔽某些账号的主题帖

### ISSUE THREAD

**Issue by OuroborosCaster** [ymback/NGA-CLIENT-VER-OPEN-SOURCE#136]
就是在版面连帖子都看不到的那种，有些垃圾号发的帖看着标题就恶心，还不好关键字屏蔽，希望能根据发帖人来进行屏蔽，直接看不见

**Comment by ymback** [comment]
打开，找到这个人，楼层右下角三个点，屏蔽此人
