### ISSUE TITLE
求求你们对nuke.php post gbk好不好(

### ISSUE THREAD

**Issue by DieMoe233** [ymback/NGA-CLIENT-VER-OPEN-SOURCE#155]
这边版务，每次上网页版受理举报看到举报理由等信息全都是乱码，要抓狂了(
nuke.php受理的字符串编码是gbk格式，post utf8会导致版务后台显示是乱码

**Comment by Justwen** [comment]
已经改成GBK了，这个接口不方便调试，所以方便再确认下？

**Comment by force0119** [comment]
邮件已收到。3Q
