### ISSUE TITLE
无法取消收藏"我的收藏"中的自定义板块

### ISSUE THREAD

**Issue by yukiloh** [ymback/NGA-CLIENT-VER-OPEN-SOURCE#161]
[![7QMezD.jpg](https://s4.ax1x.com/2022/01/13/7QMezD.jpg)](https://imgtu.com/i/7QMezD)
如图↑
误操作添加了**骑马**板块,也不知道如何删除
如果是已有板块则可以通过页面内的五角星来取消,但这类错误订阅的板块没有办法取消

**Comment by force0119** [comment]
邮件已收到。3Q
