### ISSUE TITLE
很多帖子打开失败，NGA估计对接口做了手脚

### ISSUE THREAD

**Issue by vangogh-ken** [ymback/NGA-CLIENT-VER-OPEN-SOURCE#165]
很多帖子打开失败，直接使用postman调用，返回的数据不全，内容被截断了，导致客户端无法解析

**Comment by elrondliu** [comment]
这个是NGA接口的调整，我们也没办法

**Comment by machine-doll** [comment]
现在NGA似乎是直接把网页版停了  
已经没有办法在不用它的那个全是广告的客户端的前提下上NGA了

**Comment by ymback** [comment]
设置里换成178的URL，USER AGENT改下，Nga_Official即可
