### ISSUE TITLE
帖子看不到回复，全部显示为0

### ISSUE THREAD

**Issue by yongliyongli** [ymback/NGA-CLIENT-VER-OPEN-SOURCE#169]
目前网页版也只有https://nga.178.com/可以看到回复

**Comment by AuroraYu** [comment]
In settings change the domain from the default ”bbs.nga.cn” to ”nga.178.com”, it will work

**Comment by yongliyongli** [comment]
> In settings change the domain from the default ”bbs.nga.cn” to ”nga.178.com”, it will work
> 

wow ,  u gays r real heroes~

**Comment by xc1988** [comment]
这下好像彻底看不到了

**Comment by xiaoyaoyuxin** [comment]
178也不行了。

**Comment by ymback** [comment]
去更新最新版，修改UA
