### ISSUE TITLE
178的域名也gg了

### ISSUE THREAD

**Issue by WMDantibirth** [ymback/NGA-CLIENT-VER-OPEN-SOURCE#170]
这下咋整

**Comment by reficul-fake** [comment]
方案一 (感谢KarmaU)
win10以上可以用第三方uwp，[https://www.microsoft.com/store/productId/9P3LT89T4SRS]

方案二 (感谢Rebellion x)
使用插件或者脚本直接改用户UA参数
例如Chrome系浏览器可以找User Agent Switcher & Manager
然后将用户代理串改成NGA_WP_JW/(;WINDOWS)

**Comment by machine-doll** [comment]
我这边网页版完全没法上nga了  
猜测是nga最近直接把网页版停用了。而这个第三方客户端其实是调用的网页版的API

**Comment by noob3004** [comment]
> 我这边网页版完全没法上nga了 猜测是nga最近直接把网页版停用了。而这个第三方客户端其实是调用的网页版的API

只能用custom user agent装成客户端了

NGA_WP_JW/(;WINDOWS)

**Comment by ymback** [comment]
晚点去PLAY更新

**Comment by WMDantibirth** [comment]
太棒了, 这就解决了
