### ISSUE TITLE
最近发帖/回帖会提示发帖失败

### ISSUE THREAD

**Issue by PaleNeutron** [ymback/NGA-CLIENT-VER-OPEN-SOURCE#178]
提示失败，但是实际成功

**Comment by yukiloh** [comment]
的确,因为发帖失败就连续点了几下傻眼了

**Comment by mlzzen** [comment]
> 的确,因为发帖失败就连续点了几下傻眼了

我这个版本修复了，且加了一个自动签到的功能

**Comment by thouser8** [comment]
> > 的确，因为发帖失败就连续点了几下傻眼了
> 
> 我这个版本修复了，且加了一个自动签到的功能

请问你是在哪里下载的？

**Comment by mlzzen** [comment]
> > > 的确，因为发帖失败就连续点了几下傻眼了
> > 
> > 
> > 我这个版本修复了，且加了一个自动签到的功能
> 
> 请问你是在哪里下载的？

我自己打包发版的 https://github.com/mlzzen/open-nga/releases/tag/v3.8.6
