### ISSUE TITLE
开源版福利:萌爱自拍  这个挂了，代码没移除吗？

### ISSUE THREAD

**Issue by TheStar4Fate** [ymback/NGA-CLIENT-VER-OPEN-SOURCE#87]
重新搞了个项目试了下，已经GG了

**Comment by Justwen** [comment]
反正也不参加编译，就没管了

**Comment by TheStar4Fate** [comment]
![q581f xfv bt6f4 xgd c](https://user-images.githubusercontent.com/7358871/42311151-bd07d6da-806f-11e8-8311-aa1150330f10.jpg)
