### ISSUE TITLE
登录这块有些疑问，望指点

### ISSUE THREAD

**Issue by KinoshitaHanson** [ymback/NGA-CLIENT-VER-OPEN-SOURCE#99]
登录这块，是在论坛申请了客户端验证码么？ 还是通过别的什么方式实现的？ 望指点一下。 由于不是安卓开发，代码看了半天也没整明白。闲来没事，想做个小程序玩玩，在登录这边卡住了。

**Comment by fallenwood** [comment]
~~巧了我也在登录这边卡住了~~
~~当时我还在其他看着像登录的代码里打了断点~~
大概是通过内嵌官方的登录网页进行登录，存储cookie信息保持登录状态的
~~说错了别打我~~

**Comment by Justwen** [comment]
就是这样实现的

**Comment by KinoshitaHanson** [comment]
我试了登录接口，登录可以成功，但是token什么的，他都放在http头的cookie上返回给我，但是这个又是302重定向，我拿不到那个header信息。
由于是小程序（H5），如果内嵌官方的登录页登录，我也拿不到cookie，就获取不到token。 
看来计划流产了啊
